version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/monthly_money_manager
permissions:
  - object: /var/www/monthly_money_manager
    owner: rails
    group: rails
    mode: 744
hooks:
  BeforeInstall:
    - location: scripts/docker_pull.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root