version: '2'
services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/monthly_money_manager_app:latest
    command: bundle exec "unicorn -p 3000 -c /app/config/unicorn.rb"
    ports:
      - '3000:3000'
    volumes:
      - /var/tmp
      - /var/log/monthly_money_manager:/app/log
      - /app/public
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/monthly_money_manager_nginx:latest
    ports:
      - '80:80'
    volumes_from:
      - app